
CREATE DATABASE TEST_ORIONTEK;

CREATE TABLE CLIENTE (
  IDCLIENTE numeric(8) NOT NULL PRIMARY KEY IDENTITY,
  NOMBRE VARCHAR(60) NULL DEFAULT NULL,
  APELLIDO VARCHAR(60) NULL DEFAULT NULL)


CREATE TABLE PAIS (
  IDPAIS numeric(3) NOT NULL PRIMARY KEY IDENTITY,
  DESCRIPCION VARCHAR(60) NULL DEFAULT NULL)


CREATE TABLE PROVINCIA (
  IDPROVINCIA numeric(6) NOT NULL PRIMARY KEY IDENTITY,
  DESCRIPCION VARCHAR(60) NULL DEFAULT NULL,
  IDPAIS numeric(3) Not NULL FOREIGN KEY REFERENCES PAIS(IDPAIS))

  CREATE TABLE SECTOR (
  IDSECTOR numeric(6) NOT NULL PRIMARY KEY IDENTITY,
  DESCRIPCION VARCHAR(60) NULL DEFAULT NULL,
  IDPROVINCIA numeric(6) Not NULL FOREIGN KEY REFERENCES PROVINCIA(IDPROVINCIA))

  CREATE TABLE DIRECCION_CLIENTE(
	IDDIRCLIENTE numeric (6) NOT NULL PRIMARY KEY IDENTITY,
	IDCLIENTE numeric(8) NOT NULL FOREIGN KEY REFERENCES CLIENTE(IDCLIENTE),
	IDSECTOR numeric(6) NOT NULL FOREIGN KEY REFERENCES SECTOR(IDSECTOR),
	CALLE  VARCHAR(30) NULL DEFAULT NULL,
	DIRECCION VARCHAR(60) NULL DEFAULT NULL
  )
